In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
tips=pd.read_csv('tips_ready.csv')

In [44]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='object')

In [45]:
tips.head()

Unnamed: 0  total_bill       tip  sex  smoker       day  time  size
0           0    0.291579  0.001111  0.0     0.0  0.666667   0.0   0.2
1           1    0.152283  0.073333  1.0     0.0  0.666667   0.0   0.4
2           2    0.375786  0.277778  1.0     0.0  0.666667   0.0   0.4
3           3    0.431713  0.256667  1.0     0.0  0.666667   0.0   0.2
4           4    0.450775  0.290000  0.0     0.0  0.666667   0.0   0.6

In [32]:
#labelled data : both input and output are given
#unlabelled data : only input is given
tips.drop('Unnamed: 0',axis=1,inplace=True)

In [47]:
x=tips.drop('tip',axis=1)

In [48]:
y=tips['tip']

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error


In [55]:
#split train and test data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [56]:
#create an instance of lineear regression model
model=LinearRegression()


In [57]:
#train the model
model.fit(x_test,y_test)

LinearRegression()

In [60]:
y_prediction=model.predict(x_test)

In [62]:
new_data=pd.DataFrame({'Unnamed: 0':[243],'total_bill':[50],'sex':[2],'smoker':[3],'day':[4],'time':[5],'size':[2]})

In [64]:
new_predict=model.predict(new_data)
new_predict

array([25.69214548])

In [65]:
df=sns.load_dataset('flights')

In [66]:
df.head()

year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [71]:
df1=pd.DataFrame(df.groupby('year')['passengers'].sum())
df1.reset_index(inplace=True)

In [72]:
df1

year  passengers
0   1949        1520
1   1950        1676
2   1951        2042
3   1952        2364
4   1953        2700
5   1954        2867
6   1955        3408
7   1956        3939
8   1957        4421
9   1958        4572
10  1959        5140
11  1960        5714

In [73]:
#predict the passengers for the yearwise

In [75]:
x=df1['year']
y=df1['passengers']

In [76]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [77]:
model=LinearRegression()


In [79]:
model.fit(x_test,y_test)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [80]:
# this is the assignments


In [81]:
#...........new work...............

In [82]:
#one hot encoder 
#lable encoder 
#one hotr encoder is used for the categorical data for that we use get dummies 

In [98]:
tips=pd.get_dummies(tips)

In [99]:
tips 

Unnamed: 0  total_bill       tip  sex  smoker       day  time  size
0             0    0.291579  0.001111  0.0     0.0  0.666667   0.0   0.2
1             1    0.152283  0.073333  1.0     0.0  0.666667   0.0   0.4
2             2    0.375786  0.277778  1.0     0.0  0.666667   0.0   0.4
3             3    0.431713  0.256667  1.0     0.0  0.666667   0.0   0.2
4             4    0.450775  0.290000  0.0     0.0  0.666667   0.0   0.6
..          ...         ...       ...  ...     ...       ...   ...   ...
239         239    0.543779  0.546667  1.0     0.0  0.333333   0.0   0.4
240         240    0.505027  0.111111  0.0     1.0  0.333333   0.0   0.2
241         241    0.410557  0.111111  1.0     1.0  0.333333   0.0   0.2
242         242    0.308965  0.083333  1.0     0.0  0.333333   0.0   0.2
243         243    0.329074  0.222222  0.0     0.0  1.000000   0.0   0.2

[244 rows x 8 columns]

In [85]:
#separate x and y
x=tip1.drop('tip',axis=1)
y=tip1['tip']

In [86]:
x

Unnamed: 0  total_bill  sex  smoker       day  time  size
0             0    0.291579  0.0     0.0  0.666667   0.0   0.2
1             1    0.152283  1.0     0.0  0.666667   0.0   0.4
2             2    0.375786  1.0     0.0  0.666667   0.0   0.4
3             3    0.431713  1.0     0.0  0.666667   0.0   0.2
4             4    0.450775  0.0     0.0  0.666667   0.0   0.6
..          ...         ...  ...     ...       ...   ...   ...
239         239    0.543779  1.0     0.0  0.333333   0.0   0.4
240         240    0.505027  0.0     1.0  0.333333   0.0   0.2
241         241    0.410557  1.0     1.0  0.333333   0.0   0.2
242         242    0.308965  1.0     0.0  0.333333   0.0   0.2
243         243    0.329074  0.0     0.0  1.000000   0.0   0.2

[244 rows x 7 columns]

In [87]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [88]:
model_cat_test=LinearRegression()

In [89]:
model_cat_test.fit(x_test,y_test)

LinearRegression()

In [90]:
y_pred=model_cat_test.predict(x_test)

In [91]:
y_pred

array([ 2.02496192e-01,  1.06152204e-01,  2.01984656e-01,  2.55359409e-01,
        1.51583205e-01,  1.87868829e-01,  3.06466643e-01,  1.05591452e-01,
        1.68250733e-01,  1.96061448e-01,  1.84674759e-01, -1.47247829e-02,
        9.02094326e-02,  1.51069261e-01,  9.76313912e-02,  1.64971034e-01,
        2.05178174e-01,  2.37002251e-01,  1.54958965e-01,  4.07609019e-01,
        2.32508009e-01,  2.20905581e-01,  1.90658191e-01,  8.99344252e-02,
        2.33335447e-01,  8.69250810e-02,  1.19767239e-01,  3.28037116e-01,
        1.12896959e-01,  4.64524910e-01,  3.62649686e-01,  4.51261544e-02,
        1.93959770e-01,  2.69973971e-01,  2.05586914e-01,  2.45093444e-01,
        1.50203395e-01,  4.85376212e-01,  1.04123276e-01,  1.90382745e-01,
        7.40584070e-02,  1.25521630e-01,  2.05394821e-01,  1.36217284e-01,
        1.11895364e-01,  8.89080709e-02,  1.16960811e-01,  1.89078392e-01,
       -3.97581050e-04])

In [94]:
new_data=pd.DataFrame({'Unnamed: 0':[24],'total_bill':[5],'sex':[2],'smoker':[3],'day':[4],'time':[5],'size':[2]})

In [95]:
pred=model_cat_test.predict(new_data)
pred

array([3.00032648])