In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

In [2]:
data=pd.read_csv(r'tips_ready.csv')

In [3]:
X=data.drop('tip', axis=1)
y=data['tip']

In [4]:
#split train and test data
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [5]:
#create an instance of linear regression
tips_linear=LinearRegression()

In [6]:
tips_linear.fit(X_train, y_train)

LinearRegression()

In [7]:
#prediction
y_pred=tips_linear.predict(X_test)

In [8]:
y_pred

array([ 0.22303525,  0.10778529,  0.31997095,  0.31413154,  0.12974376,
        0.17736092,  0.29410707,  0.14566534,  0.17030368,  0.15296625,
        0.20533597,  0.1196658 ,  0.126892  ,  0.14177197,  0.09533449,
        0.23595042,  0.21936034,  0.24092737,  0.1829334 ,  0.52839018,
        0.28260569,  0.25892747,  0.14062382,  0.11572179,  0.2321712 ,
        0.14076119,  0.12324837,  0.2565306 ,  0.23569445,  0.6201039 ,
        0.43565071,  0.07058552,  0.25608832,  0.20823475,  0.21660953,
        0.32084793,  0.12137674,  0.49770114,  0.15210537,  0.22522136,
        0.12378399,  0.16680058,  0.26139682,  0.14748081,  0.10526036,
       -0.00175067,  0.0992968 ,  0.23767535,  0.09446886])

In [9]:
data

Unnamed: 0  total_bill       tip  sex  smoker       day  time  size
0             0    0.291579  0.001111  0.0     0.0  0.666667   0.0   0.2
1             1    0.152283  0.073333  1.0     0.0  0.666667   0.0   0.4
2             2    0.375786  0.277778  1.0     0.0  0.666667   0.0   0.4
3             3    0.431713  0.256667  1.0     0.0  0.666667   0.0   0.2
4             4    0.450775  0.290000  0.0     0.0  0.666667   0.0   0.6
..          ...         ...       ...  ...     ...       ...   ...   ...
239         239    0.543779  0.546667  1.0     0.0  0.333333   0.0   0.4
240         240    0.505027  0.111111  0.0     1.0  0.333333   0.0   0.2
241         241    0.410557  0.111111  1.0     1.0  0.333333   0.0   0.2
242         242    0.308965  0.083333  1.0     0.0  0.333333   0.0   0.2
243         243    0.329074  0.222222  0.0     0.0  1.000000   0.0   0.2

[244 rows x 8 columns]

In [10]:
#using real world data
new_data=pd.DataFrame({'Unnamed: 0':[243],'total_bill':[50],'sex':[0],'smoker':[0], 'day':[1],'time':[0] ,'size':[2],'col':[2]})

In [11]:
new_predict=tips_linear.predict(new_data)
new_predict

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- col


In [12]:
#flights
flights=sns.load_dataset('flights')

In [13]:
flights

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [14]:
df=flights.groupby('year')['passengers'].sum().reset_index()

In [15]:
df

year  passengers
0   1949        1520
1   1950        1676
2   1951        2042
3   1952        2364
4   1953        2700
5   1954        2867
6   1955        3408
7   1956        3939
8   1957        4421
9   1958        4572
10  1959        5140
11  1960        5714

In [16]:
df.columns

Index(['year', 'passengers'], dtype='object')

<h1>HOMEWORK</h1>

In [17]:
#predict the passengers yearwise(assignment)
X=df.drop('passengers', axis=1)
y=df['passengers']

In [18]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)

In [19]:
passengers_linear=LinearRegression()

In [20]:
passengers_linear.fit(X_train, y_train)

LinearRegression()

In [21]:
pass_pred=passengers_linear.predict(X_test)
pass_pred

array([5164.65782123, 4761.14804469, 1129.56005587])

In [22]:
input_data=pd.DataFrame({'year':[2000]})

In [23]:
new_pass_pred=passengers_linear.predict(input_data)
new_pass_pred

array([21708.55865922])

<h1>End</h1>

In [24]:
#categorical values
data1=sns.load_dataset('tips')

In [25]:
data1

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
data1=pd.get_dummies(data1)

In [27]:
data1

total_bill   tip  size  sex_Male  sex_Female  smoker_Yes  smoker_No  \
0         16.99  1.01     2     False        True       False       True   
1         10.34  1.66     3      True       False       False       True   
2         21.01  3.50     3      True       False       False       True   
3         23.68  3.31     2      True       False       False       True   
4         24.59  3.61     4     False        True       False       True   
..          ...   ...   ...       ...         ...         ...        ...   
239       29.03  5.92     3      True       False       False       True   
240       27.18  2.00     2     False        True        True      False   
241       22.67  2.00     2      True       False        True      False   
242       17.82  1.75     2      True       False       False       True   
243       18.78  3.00     2     False        True       False       True   

     day_Thur  day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0       False    False    False     True       False         True  
1       False    False    False     True       False         True  
2       False    False    False     True       False         True  
3       False    False    False     True       False         True  
4       False    False    False     True       False         True  
..        ...      ...      ...      ...         ...          ...  
239     False    False     True    False       False         True  
240     False    False     True    False       False         True  
241     False    False     True    False       False         True  
242     False    False     True    False       False         True  
243      True    False    False    False       False         True  

[244 rows x 13 columns]

In [28]:
X=data1.drop('tip', axis=1)
y=data1['tip']

In [29]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42) 

In [30]:
tips1_linear=LinearRegression()

In [31]:
tips1_linear.fit(X_train, y_train)

LinearRegression()

In [32]:
y_pred=tips1_linear.predict(X_test)

In [33]:
y_pred

array([2.91436632, 2.00292613, 3.96425583, 3.76380832, 2.14836306,
       2.67423448, 3.63934628, 2.29147245, 2.57207155, 2.45851225,
       2.90446763, 2.0573337 , 2.11817193, 2.35130838, 1.82976215,
       3.10830675, 2.95140176, 3.21602976, 2.56640892, 5.73957295,
       3.43490366, 3.22645102, 2.17139823, 1.94180002, 3.16394533,
       2.24547894, 2.14497574, 3.21025435, 3.20097595, 6.66803147,
       5.01111235, 1.57804024, 3.1909877 , 2.76652194, 2.98412862,
       3.85695724, 2.17008741, 5.46673999, 2.35586827, 2.99190732,
       2.03271177, 2.48465991, 3.44046814, 2.35532237, 1.92528104,
       0.87348926, 1.81911521, 3.04083954, 1.85436902])

In [34]:
data1.columns

Index(['total_bill', 'tip', 'size', 'sex_Male', 'sex_Female', 'smoker_Yes',
       'smoker_No', 'day_Thur', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Lunch',
       'time_Dinner'],
      dtype='object')

In [35]:
brand_new_data=pd.DataFrame({'total_bill':[29.03], 'size':[2], 'sex_Male':[True], 'sex_Female':[False], 'smoker_Yes':[True],
       'smoker_No':[False], 'day_Thur':[True], 'day_Fri':[False], 'day_Sat':[False], 'day_Sun':[True], 'time_Lunch':[False],
       'time_Dinner':[True]})

In [36]:
new_prediction=tips1_linear.predict(brand_new_data)
new_prediction

array([3.65354349])

<h1>doing the same prediction by taking user input and encoding</h1>

In [37]:
data={'total_bill':[29.03],'size':[2],'sex':'Male','day':'Sun','time':'Dinner','smoker':'Yes'}

In [38]:
new_data=pd.DataFrame(data, index=[0])

In [39]:
new_data

total_bill  size   sex  day    time smoker
0       29.03     2  Male  Sun  Dinner    Yes

In [40]:
X_train.head(1)

total_bill  size  sex_Male  sex_Female  smoker_Yes  smoker_No  day_Thur  \
228       13.28     2      True       False       False       True     False   

     day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
228    False     True    False       False         True

In [41]:
new_data=pd.get_dummies(new_data)

In [42]:
new_data

total_bill  size  sex_Male  day_Sun  time_Dinner  smoker_Yes
0       29.03     2      True     True         True        True

In [43]:
for cols in X_train.columns:
    if cols not in new_data.columns:
        new_data[cols]=0

In [44]:
new_data

total_bill  size  sex_Male  day_Sun  time_Dinner  smoker_Yes  sex_Female  \
0       29.03     2      True     True         True        True           0   

   smoker_No  day_Thur  day_Fri  day_Sat  time_Lunch  
0          0         0        0        0           0

In [45]:
new_data=new_data[X_train.columns]#ordering the columns in the dataframe

In [46]:
new_data

total_bill  size  sex_Male  sex_Female  smoker_Yes  smoker_No  day_Thur  \
0       29.03     2      True           0        True          0         0   

   day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0        0        0     True           0         True

In [47]:
new_pred=tips1_linear.predict(new_data)
new_pred

array([3.72918955])

In [ ]:
#cars data 

In [48]:
data11=pd.read_csv(r'cars_eda_analysis.csv')

In [49]:
data11.head()

Unnamed: 0    Location  Year  Kilometers_Driven Fuel_Type Transmission  \
0           1        Pune  2015              41000    Diesel       Manual   
1           2     Chennai  2011              46000    Petrol       Manual   
2           3     Chennai  2012              87000    Diesel       Manual   
3           4  Coimbatore  2013              40670    Diesel    Automatic   
4           6      Jaipur  2013              86999    Diesel       Manual   

  Owner_Type  Mileage  Engine   Power  Seats    brand   model  
0      First    19.67  1582.0  126.20    5.0  Hyundai   Creta  
1      First    18.20  1199.0   88.70    5.0    Honda    Jazz  
2      First    20.77  1248.0   88.76    7.0   Maruti  Ertiga  
3     Second    15.20  1968.0  140.80    5.0     Audi      A4  
4      First    23.08  1461.0   63.10    5.0   Nissan   Micra

In [1]:
#import decision tree algorithm
from sklearn.tree import DecisionTreeClassifier

In [2]:
mkc=DecisionTreeClassifier()


In [4]:
mkc.fit(x_train, y_train)

NameError: name 'x_train' is not defined